ideastore/config/routes.rb
Rails.application.routes.draw do
  get "pages/home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "pages#home"
  resources :ideas
end

ideastore/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

ideastore/app/models/idea.rb
class Idea < ApplicationRecord
end

ideastore/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ideastore/app/controllers/ideas_controller.rb
# app/controller/ideas_controller.rb
class IdeasController < ApplicationController
  def show
    @idea = Idea.find(params[:id])
  end

  def index
    @ideas = Idea.all
  end

  def new
  end

  def create
    @idea = Idea.new(idea_params)

    if @idea.save
      redirect_to @idea
    else
      render "new"
    end
  end

  def edit
    @idea = Idea.find(params[:id])
  end

  def update
    @idea = Idea.find(params[:id])

    if @idea.update(idea_params)
      redirect_to @idea
    else
      render "edit"
    end
  end

  def destroy
    @idea = Idea.find(params[:id])
    @idea.destroy

    redirect_to ideas_path
  end

  private

  def idea_params
    params.require(:idea).permit(:title, :description)
  end
end

ideastore/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

ideastore/app/helpers/application_helper.rb
module ApplicationHelper
end

ideastore/app/helpers/pages_helper.rb
module PagesHelper
end

ideastore/app/views/ideas/edit.html.erb
<main class="ideas">
  <section class="text-center">
    <div class="container">
      <h1>Edit Idea</h1>

      <%= form_with model: @idea, local: true do |form| %>
        <p>
          <%= form.label :title %><br>
          <%= form.text_field :title, placeholder: 'your idea title ...' %>
        </p>

        <p>
          <%= form.label :description %><br>
          <%= form.text_area :description, placeholder: 'your idea description ...' %>
        </p>

        <p>
          <%= form.submit %>
        </p>
      <% end %>

      <p>
        <%= link_to  "Cancel and return", ideas_path, class: 'btn btn-primary' %>
      </p>
    </div>
  </section>
</main>

ideastore/app/views/ideas/index.html.erb
<main class="ideas">
  <section class="text-center">
    <div class="container">
      <h1>All awesome ideas</h1>

      <table>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th colspan="3">Actions</th>
        </tr>

        <% @ideas.each do |idea| %>
          <tr>
            <td><%= idea.title %></td>
            <td><%= idea.description %></td>
            <td><%= link_to 'Show', idea_path(idea) %></td>
            <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
            <td><%= link_to 'Delete', idea_path(idea), method: :delete, data: { confirm: 'Are you sure, you want to delete this idea?' } %></td>
          </tr>
        <% end %>
      </table>

      <p>
        <%= link_to  "Create An Idea", new_idea_path, class: 'btn btn-primary' %>
      </p>
    </div>
  </section>
</main>

ideastore/app/views/ideas/new.html.erb
<main class="ideas">
  <section class="text-center">
    <div class="container">
      <h1>New Idea</h1>

      <%= form_with scope: :idea, url: ideas_path, local: true do |form| %>
        <p>
          <%= form.label :title %><br>
          <%= form.text_field :title, placeholder: 'your idea title ...' %>
        </p>

        <p>
          <%= form.label :description %><br>
          <%= form.text_area :description, placeholder: 'your idea description ...' %>
        </p>

        <p>
          <%= form.submit %>
        </p>
      <% end %>
    </div>
  </section>
</main>

ideastore/app/views/ideas/show.html.erb
<main class="ideas">
  <section class="text-center">
    <div class="container">
      <h1>Idea</h1>
      <div class="idea">
        <div class="title">
          <strong>Title: </strong> <%= @idea.title %>
        </div>
        <div class="description">
          <strong>Description: </strong>
          <p>
            <%= @idea.description %>
          <p>
        </div>
      </div>

      <p>
        <%= link_to  "Back to all ideas", ideas_path, class: 'btn btn-primary' %>
      </p>
    </div>
  </section>
</main>

ideastore/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ideastore</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "pages", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "ideas", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>
    <header id="home">
        <!-- Navbar -->
        <nav id="navbar">
          <div class="container">
            <h1 class="logo">
              <%= link_to "Idea Store", root_path %>
            </h1>
            <ul>
              <li>
                <%= link_to  "Home", root_path, class: 'active' %>
              </li>
              <li>
                <%= link_to  "Ideas", ideas_path %>
              </li>
            </ul>
          </div>
        </nav>
    </header>      
    <%= yield %>
  </body>
</html>

ideastore/app/views/pages/home.html.erb
<!-- Header -->
<main>
  <section class="jumbotron text-center">
    <div class="container">
      <h1>Idea Store</h1>
      <p class="lead text-muted">
        A place to share awesome ideas with awesome people.
        Get your idea validated by people, work on it and build your next startup!
      </p>
      <p>
        <%= link_to  "Visit all ideas", ideas_path, class: 'btn btn-primary' %>
      </p>
    </div>
  </section>
</main>